var mongoose = require('mongoose');

var SDETSchema = new mongoose.Schema({
  EmpNum:
  { type: String,
    required: true
  }, 
  Source: String,
  AssignAccount: String,
  JlEmail: String,
  MasterCustomer: String,
  Portfolio: String,
  DU:String,
  AccountSpoke:String,
  site:String,
  SdetFoundation:String,
  certisCompleted:Number,
  FssFplanDate:Date,
  FssfActualDate:Date,
  Sdettag:String,
  AgilePlanDate:Date,
  AgileActualDate:Date,
  AgileCompletionDate:Date,
  AgileStatus:String,
  AgileCertificationName:String,
  AutomationTool:String,
  AutomationToolPlanDate:Date,
  AutomationToolActualDate:Date,
  AutomationToolCompletionDate:Date,
  AutomationToolStatus:String,
  AutomationToolCertificationName:String,
  ProgrammingLanguage:String,
  PrgLangPlanDate:Date,
  PrgLangActualDate:Date,
  PrgLangCompletionDate:Date,
  PrgLangStatus:String,
  ProgLangCertificationName:String,
  DevOpsProfessional:String,
  DevOpsPlanDate:Date,
  DevOpsActualPlanDate:Date,
  DevOpsCompletionDate:Date,
  DevOpsStatus:String,
  CertificationName:String,
  BDDTool:String,
  BDDPlanDate:Date,
  BDDPActualPlanDate:Date,
  BDDCompletionDate:Date,
  BDDStatus:String,
  FrontEndLanguage:String,
  FrontPlanDate:Date,
  FrontActualPlanDate:Date,
  FrontCompletionDate:Date,
  FrontEndStatus:String,
  CloudPlanDate:Date,
  CloudActualPlanDate:Date,
  CloudCompletionDate:Date,
  CloudStatus:String,
  API:String,
  APIPlanDate:Date,
  APIActualPlanDate:Date,
  APICompletionDate:Date,
  APIStatus:String,
  DB:String,
  DBPlanDate:Date,
  DBActualPlanDate:Date,
  DBCompletionDate:Date,
  DBStatus:String,
  EmpName: 
  { 
    type: String,
    required: true
  },
  EmpRoleCode:String,
  ActDesc:String,
  Role:String,
  Location:String,
  City:String,
  ProjectCode:String,
  EmpBandCode:Number
});

module.exports = mongoose.model('Employee', SDETSchema);