var mongoose = require('mongoose');

var readcsv_db = new mongoose.Schema({
ParticipantId : String, 
ParticipantMailId : String, 
ParticipantIBU : String,
ParticipantPU: String, 
ParticipantJL : String,
ParticipantLocation: String,
ParticipantAccount: String,
ParticipantCountry: String,
ParticipantCU: String,
ParticipantDU : String,
InstructorId : String, 
InstructorMailId : String,
CourseCode: String,
CourseOfferingId: String,
DepartmentCode: String, 
Source: String,
DateActionPerformed: String,
TrainingHours: String,
Duration: String,
Horizon: String, 
ItemId: String, 
Location: String,
OfferingMode: String, 
isCompleted: String, 
ABCD: String,
SkillName: String, 
ServiceLine : String, 
NewServiceLine : String, 
Stacks : String, 
StacksCompleted : String,
Status : String,
CourseTitle : String, 
Topics : String,
TrackName : String, 
assessmentScore : String, 
devices : String, 
isCurrent : String,
isStaging : String,
lex_collection : String,
lex_course : String, 
lex_program :String,
lex_resource : String,
lexId : String, 
OnsiteOffshore : String, 
projectCode : String, 
projectType : String,
});

module.exports = mongoose.model('categories', readcsv_db,'category');